import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/custom/header";
import StoreProvider from "./StoreProvider";
import { Toaster } from "@/components/ui/toaster";
import Refresher from "@/components/custom/refresher";
import QueryProvider from "./QueryProvider";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body
          className={cn(
            "min-h-screen font-manrope bg-background antialiased",
            manrope.variable
          )}
        >
          <QueryProvider>
            <Refresher>
              {/* Header */}
              <Header />
              {/* Childrens */}
              {children}
              <Toaster />
            </Refresher>
          </QueryProvider>
        </body>
      </StoreProvider>
    </html>
  );
}
